networks:
  loki:
    driver: bridge

services:
  promtail:
    image: grafana/promtail:latest
    ports: 
      - "9080:9080" 
    networks:
      - loki
    depends_on:
      - loki
    volumes:
      - "./promtail/config/config.yaml:/etc/promtail/config/config.yaml"
      - "./var/log:/logs/syslogs/"
      - "./promtail/position:/position"

  loki:
    image: grafana/loki:latest
    ports: 
      - "3100:3100" 
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true 
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
    networks:
      - loki
